package: d2u_guestbook
version: '1.0.12'
author: Tobias Krais
supportpage: http://github.com/tobiaskrais/d2u_guestbook

page:
    title: 'translate:d2u_guestbook'
    perm: 'd2u_guestbook[]'
    icon: rex-icon fa-book
    subpages:
        entries: { title: 'translate:d2u_guestbook_entries', icon: rex-icon fa-book, perm: 'd2u_guestbook[]' }
        setup: { title: 'translate:d2u_helper_setup', icon: rex-icon rex-icon-install, itemClass: pull-right, perm: 'd2u_guestbook[settings]' }
        settings: { title: 'translate:d2u_helper_settings', icon: rex-icon rex-icon-system, itemClass: pull-right, perm: 'd2u_guestbook[settings]' }

requires:
    redaxo: '>=5.10.0'
    packages:
        d2u_helper: '>=1.5.2'
        sprog: '>=1.0.0'
        yform: '>=3.0'
    php: '>=7.4'

default_config:
    allow_answer: 'false'
    no_entries_page: 10

installer_ignore:
    - .github