package: d2u_guestbook
version: '1.0.0'
author: Tobias Krais
supportpage: http://github.com/tobiaskrais/d2u_guestbook

page:
    title: 'translate:d2u_guestbook'
    perm: d2u_guestbook[]
    icon: rex-icon fa-book
    subpages:
        entries: { title: 'translate:d2u_guestbook_entries', icon: rex-icon fa-book, perm: d2u_guestbook[] }
        settings: { title: 'translate:d2u_guestbook_settings', icon: rex-icon rex-icon-system, perm: d2u_guestbook[settings] }
        setup: { title: 'translate:d2u_guestbook_setup', icon: rex-icon rex-icon-install, perm: d2u_guestbook[settings] }

requires:
    redaxo: '>=5.3.0'
    php:
        version: '>=5.6'
    packages:
        d2u_helper: '>=1.2.1'
        emailobfuscator: '>=2.1'
        sprog: '>=1.0.0'
        yform: '>=2.0'